
#PBS -N ts-6
#PBS -l walltime=999:00:00
#PBS -j oe
#PBS -l nodes=1:ppn=8
#PBS -V

user="lijie"

WORK_DIR=$PBS_O_WORKDIR/ts_workspace
TMP_DIR="/state/partition1/scratch/$user/$PBS_JOBID"

cd $PBS_O_WORKDIR
mkdir -p $TMP_DIR

istart=26
iend=30

for ((i=${istart}; i<=${iend}; i++))
do
  cp -r $WORK_DIR/${i} $TMP_DIR/${i}
done

cd $TMP_DIR

for ((i=${istart}; i<=${iend}; i++))
do
  cd ${i}
  g16 *.gjf >> error 2>&1
  cd ..
  cp -rf $TMP_DIR/${i} $WORK_DIR/
done

rm -rf $TMP_DIR
